### ISSUE TITLE
Knife bug (compatibility with WeaponPaints)

### ISSUE THREAD

**Issue by criskkky** [destoer/Cs2Jailbreak#10]
Hi @destoer,

Currently i'm having some problems with compatibility of [WeaponPaints](https://github.com/Nereziel/cs2-WeaponPaints) and your plugin.

Is possible to add a feature that allows turn off weapon strip at round start?

Before using this plugin I used to apply native convars like:
```
mp_t_default_melee "weapon_knife"
mp_t_default_primary ""
mp_t_default_secondary ""

mp_ct_default_melee "weapon_knife"
mp_ct_default_primary ""
mp_ct_default_secondary ""

mp_equipment_reset_rounds 1
```
So having applied that convars for me isn't needed weapon strip at round start.
I hope you can do it bro 🙏

I left a video here showing the problem:
https://streamable.com/uj30ac

**Comment by destoer** [comment]
Sure i can add a config to turn off my plugins weapon stripping at round start.

**Comment by destoer** [comment]
Okay its implemented as its just a small change just go re download the old release, its in the config as which is defaulted to on
just set it to false if you want to switch it off

strip_spawn_weapons 

this stops it using the plugins builtin facilities along with tampering with any of the cvars

you might have to enter it manually / delete the config because it doesn't refresh automatically.

**Comment by criskkky** [comment]
Hi @destoer could we re-open this issue?, I'm having problems again, there's some other feature of this plugin that could be still removing knife at roundstart?. From round two onwards the problems begin.

**Comment by destoer** [comment]
I cant see any not tripped by lr / sd at this point.

**Comment by criskkky** [comment]
Perhaps this issue is related to WeaponPaints because in the "Issues" section, I've found people mentioning that they are experiencing the same problem. So if your plugin isn't affecting weapons at RoundStart or PlayerSpawn your plugin its ok.

https://github.com/Nereziel/cs2-WeaponPaints/issues/120

**Comment by criskkky** [comment]
Hi @destoer, I modified and compiled WeaponPaints and seems thats 100% problem from that plugin, sorry for inconveniences.
