### ISSUE TITLE
MagForMag and ShotForShot are confused

### ISSUE THREAD

**Issue by VortDyn** [destoer/Cs2Jailbreak#26]
In the game, if you select "Shot for Shot" mode, the entire clip is dispensed, but if you select "Mag for Mag" 1 round is dispensed

**Comment by destoer** [comment]
I see the issue it's a silly typo ill correct it tomorrow thanks.

**Comment by destoer** [comment]
Fixed in https://github.com/destoer/Cs2Jailbreak/commit/8947fd287b7d8580c4a1282f690a35bdd78053ae, it will be in the next release soon.
