### ISSUE TITLE
add custom CT and T models

### ISSUE THREAD

**Issue by kakakolaka** [destoer/Cs2Jailbreak#4]
hi, is it possible to add custom models for players as on Zombie Escape server?

**Comment by destoer** [comment]
Hi their, sorry i missed this  but at present i'm not sure how general custom model support would work with the download situation,
im fairly sure they have to be packed into maps

**Comment by audiomaster99** [comment]
> Hi their, sorry i missed this but at present i'm not sure how general custom model support would work with the download situation, im fairly sure they have to be packed into maps

Is there any updates regarding custom player models, since we can use them as workshop addon?
