### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by tungsten35** [destoer/Cs2Jailbreak#41]
Hello, plugin doesn't work. Is it because the new update?

**Comment by destoer** [comment]
You need a new MM and css ver after the cs2 update it seems i havent tested its working yet though

**Comment by tungsten35** [comment]
I updated them and still doesn't work. Please test it.

**Comment by destoer** [comment]
Hi are any of your other plugins working? im not getting any major issues on my end...

**Comment by destoer** [comment]
Can you try load it in console manually and see if it pops errors? Its hard to know whats wrong with it plain does nothing. Btw i assume you updated the plugin itself after the update?

**Comment by destoer** [comment]
Can you try load it in console manually and see if it pops errors? Its hard to know whats wrong with it plain does nothing. Btw i assume you updated the plugin itself after the update?

**Comment by tungsten35** [comment]
Can you text me on Discord please? I think I did it everything correct but also I am a beginner at these thing so maybe I did a small mistake but I don't know :( tungsten35 is my nickname if you help me I would appreciate

**Comment by destoer** [comment]
problem with tr translation fixed in 3c55faad75bd214f46f83a96355c4d031f2a9c1f
