### ISSUE TITLE
[SUGGEST] Allowing VIP's to speak on roundstart

### ISSUE THREAD

**Issue by asapverneri** [destoer/Cs2Jailbreak#42]
Could you implement that 30sec mute when round start doesn't apply on VIP players?
This has been asked many times and it was an option in cs:go i believe.

**Comment by destoer** [comment]
How would you define them though custom tag?

**Comment by asapverneri** [comment]
you could define them using @css/vip in thirtySecMute

**Comment by destoer** [comment]
implemented :P
