### ISSUE TITLE
sd_cancel doesn't return knife

### ISSUE THREAD

**Issue by MaCoRko** [destoer/Cs2Jailbreak#43]
Hello, i had issue with the plugin where when i force cancel special day my weapons from SD doesn't dissapear and i don't get back knife, i thought that it was problem with me but there is not code for bringing back weapons when force canceled, thank you !

**Comment by destoer** [comment]
Fixed :P

**Comment by MaCoRko** [comment]
is it gonna be in next release or it is released in this version

**Comment by destoer** [comment]
Should have been in this version?

**Comment by destoer** [comment]
Should have been in this version?

**Comment by MaCoRko** [comment]
> Should have been in this version?

nope, still when i do !sd_cancel it gives me back item that was used in SD. Here is the clip.\

Uploading Counter-strike 2 2024.05.14 - 20.37.38.03.DVR (online-video-cutter.com).mp4…
