### ISSUE TITLE
Issue with LR Rebel

### ISSUE THREAD

**Issue by pimpmyname2** [destoer/Cs2Jailbreak#44]
There is an issue with LR Rebel. When selected it comes with output: [LR]: lr.player_name

**Comment by Jettucis** [comment]
Yeah, fix for this is to add the missing key to the language .json file(-s)
`"lr.player_name": "{0} started rebel",`

**Comment by destoer** [comment]
Thanks for letting me know, reminds me i need to add something to automatically dump entries for the other languages from English if they are missing.
