### ISSUE TITLE
LR_rebel + sd_cancel

### ISSUE THREAD

**Issue by MaCoRko** [destoer/Cs2Jailbreak#45]
Hi it's me again,

sd_cancel is still not giving back any guns and lr rebel when u start it it says lr.player.name and don't send message in chat that rebel started

**Comment by MaCoRko** [comment]
On gungame it spams in chat "playername is new simon" at the respawn

**Comment by destoer** [comment]
Hi, i dokt have any simon says function in the plugin?

**Comment by MaCoRko** [comment]
> Hi, i dont have any simon says function in the plugin?

sorry it's my bad i translated it to simon so i got used to it, i meant warden

**Comment by destoer** [comment]
Fixed both have a nice day :duck:
