### ISSUE TITLE
LRType.WAR doesn't like MP5

### ISSUE THREAD

**Issue by Jettucis** [destoer/Cs2Jailbreak#49]
For some weird reason Last Request War when selecting MP5 weapon, auto-drops the weapon + strips both players knives (okay that is probably fine since in `InitPlayerCommon` it strips players from weapons.
Any other weapon works just fine, but "MP5" for some weird reason will drop no matter what (just in `LRType.WAR`, SD works fine).

I am not 100% sure, since I haven't done debugging on that yet, but I think that the cause might be in LastRequestHook.cs `WeaponEquip` void <--- I will do some debugging in the coming days and will update this Issue if I've found something.

For now am forced to comment out `lrMenu.AddMenuOption("MP5", PickedOption);`

**Comment by destoer** [comment]
Weird... Thanks for letting me know

**Comment by Jettucis** [comment]
Don't ask me how or why because I am unable to answer it as well, but when `LRType.WAR` is initiated and started with MP5, the plugin thinks it's MP7 which is why the weapon is dropped.

**Comment by destoer** [comment]
Ah thanks i think thered a weird flag you can check for it

**Comment by destoer** [comment]
Swapped mp5 for ak47 for now thanks for the issue
